/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TodoApp;

//import controller.ProjectController;
//import java.util.Date;
//import model.Project;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        
//        ProjectController projectController = new ProjectController();
//        Project project = new Project();
//        project.setName("Projeto Teste");
//        project.setDescription("Description");
//        project.setUpdatedAt(new Date());
//        projectController.save(project);
//        project.setId(1);
//        project.setName("Novo nome do projeto");
//        project.setDescription("Nova descrição do projeto");
//        project.setUpdatedAt(new Date());
//        projectController.update(project);
//         projectController.removeById(1);
//        List<Project> projects = projectController.getAll();
//        System.out.println("Total de projetos = " + projects.size());
//
//          TaskController taskController = new TaskController();
//          
//          Task task = new Task();
//          task.setIdProject(1);
//          task.setName("Criar as telas da aplicação");
//          task.setDescription("Devem ser criadas as telas da aplicacao");
//          task.setNotes("Sem notas");
//          task.setIsCompleted(false);
//          task.setDeadline(new Date());
//          task.setUpdatedAt(new Date());
//          taskController.save(task);

//          task.setId(1);
//          task.setIdProject(1);  
//          task.setName("Novo nome do task");
//          task.setDescription("Nova descrição do task");
//          task.setNotes("sem notas");
//          task.setIsCompleted(false);
//          task.setDeadline(new Date());
//          task.setUpdatedAt(new Date());
//          taskController.update(task);
//          
//          List<Task> tasks = taskController.getAll(1);
//        
//          taskController.removeById(1);        
    }
}
